spring.application.name=E-Commerse-Platform


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.port=${PORT:8080}

# npg_efF9am2UwgZR

# Brevo Email API
brevo.api.key=${BREVO_API_KEY}

#cloudinary
cloudinary.cloud-name=exqst1oh
cloudinary.api-key=456362569414936
cloudinary.api-secret=2NVWM_3UeaInL_b-8qF2E7Lv-Z4